## Numpy Introduction and Basic Operation
NumPy, or Numerical python , is a open source python liberary for scientific and mathematical computing.

#### Importing Liberary

In [1]:
import numpy as np

#### Creating List

In [2]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


#### Diference between Python list and Numpy Array
##### Python list :
It stores only one dimentional data. Either like String, Boolean , Integer, Float.
##### Numpy Array: 
It stores multidimentional Array including String, Boolean, Integer , Float.

### Advantages of Numpy Array over Lists

In [3]:

print ('1D Array')
a = np.array([1,2,3,4,5])
print(a)

print ('2D Array')
b = np.array([[1,2,3,4,5],
             [6,7,8,9,10]])
print(b)
       


print('3D Array')
c = np.array([[[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15]]])
print(c)

1D Array
[1 2 3 4 5]
2D Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D Array
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [4]:
# Format of Defininng Numpy Array

In [5]:
type(a)

numpy.ndarray

##### Size = Tell us about the number of element present in that array.

In [6]:
print(a.size)
print(b.size)
print(c.size)

5
10
15


#####  Shape = (Rows and Colums)

In [7]:
print(a.shape)
print(b.shape)
print(c.shape) 

(5,)
(2, 5)
(1, 3, 5)


In [8]:
# (1,3,5) it incicates that 1 array of 3 rows and 5 columns.

##### dtype = Types of data present in the array

In [9]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
int32
int32


In [10]:
# we can also get float dataype as when we have any decimal number in the guven array.

d = np.array([[[1,2,3,4,5],
               [6,7,8.1,9,10],
               [11,12,13,14,15]]])
print(d.dtype)

float64
