## Some basic functions and operation

### Transpose()
##### arr.transpose()

It transpose (convert) Rows into Columns and Columns into Rows.

In [1]:
import numpy as np

In [2]:
# creating an Array first
d = np.array([[[1,2,3,4,5],
               [6,7,8.1,9,10],
               [11,12,13,14,15]]])

In [3]:
d.transpose()

array([[[ 1. ],
        [ 6. ],
        [11. ]],

       [[ 2. ],
        [ 7. ],
        [12. ]],

       [[ 3. ],
        [ 8.1],
        [13. ]],

       [[ 4. ],
        [ 9. ],
        [14. ]],

       [[ 5. ],
        [10. ],
        [15. ]]])

### np.empty()
np.empty((rows,cols),dtype)

In [4]:
# np.empty contains only two parameters That is (Tuples) and (data type)
# Tuples are here is (rows,cols)

In [5]:
np.empty((4,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
np.empty((4,4), dtype = float)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29062093e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

### np.ones()
np.ones(rows,cols),dtype)

In [7]:
x = np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [8]:
y = np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
z = np.ones((3,5), dtype = int)
z

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
a = np.ones((3,5), dtype = bool)
a

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

### np.zeros()
np.zeros((rows,cols),dtype)

In [11]:
x = np.zeros(4)
x

array([0., 0., 0., 0.])

In [12]:
y = np.zeros((4,8), dtype = int)
y

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [13]:
y = np.zeros((4,8), dtype = bool)
y

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [14]:
y = np.zeros((4,8), dtype = str)
y

array([['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '']], dtype='<U1')

In [15]:
y = np.zeros((4,8), dtype = float)
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

### np.arange()
np.arange (start,end,step)

In [16]:
# It skips the index what we define in last.
# so, here is 20 in last so it will only print from 1-19 and will skip the last digit i.e, 20.
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [17]:
# Now we will define the steps
a = np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
a = np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### arr.reshape()
arr.reshape((rows,cols))

It converts the Array into rows and columns.

In [19]:
a = a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [20]:
b = np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [21]:
b = b.reshape((10,5))
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

### Flatten()
It is the inverse process of reshaping.

It converts multidimentional array into one dimentional single array i.e, one rows and multiple columns.

In [22]:
b = b.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

### Ravel 
It is also a reverse process of reshape.

In [23]:
a = a.ravel()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### Ravel()
(1) Return only reference/view of original array.

(2) If you modify the array you would notice that the value of original array also changes.

(3) Ravel is faster than flatten.

(4) It does not occupy any memory.

(5) ravel is library-level function.

### Flatten()
(1) Return copy of original array.

(2) If you modify any value of this array value of original array is not affected.

(3) Flatten is comparatively slower than ravel().

(4) It occupies memory.

(5) Flatten is a method of ndarray object.
