### Numpy Array Slicing Operation

In [1]:
import numpy as np

In [2]:
a = np.arange(1,51)
a = a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [3]:
# printing Index Array 
# Indexing always start from zero[0] index
a[0]

array([1, 2, 3, 4, 5])

In [4]:
a[1]

array([ 6,  7,  8,  9, 10])

In [5]:
a[2]

array([11, 12, 13, 14, 15])

In [6]:
# Now we will print index values falls in that index.
a[0,0]

1

In [7]:
a[4,3]

24

In [8]:
# Now we will do slicing of index.
a[2:4]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
a[0:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [10]:
# Printing all the rows of a particular columns.
# [:,] means all the rows, 2 is columns.

a[:,2]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [11]:
# Printing  certain rows of a particular columns 

a[2:5,4]

array([15, 20, 25])

In [12]:
# Printing all rows and all columns

a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [13]:
# Printing all the rows of a particular columns

a[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [14]:
a[:, 2:5].dtype

dtype('int32')