### Numpy Mathematical Operation

In [1]:
import numpy as np

In [2]:
a = np.arange(0,18).reshape((6,3))
b = np.arange(20,38).reshape((6,3))

print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


#### Add()

In [3]:
# Addition
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [4]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

#### Subtract()

In [5]:
# Subtraction
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [6]:
a-b

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [7]:
#### 

In [8]:
# Multiplication
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

#### Division

In [9]:
# Division
a%b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [10]:
a/b

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

#### Matrix Multiplication
For matrix multiplication the the column no. of the first array and the row no. of the second array should be same(identical).

In [11]:
# Finding the shape of array, a and b

print(a.shape)
print(b.shape)

(6, 3)
(6, 3)


In [12]:
# Reshape the array

b = b.reshape((3,6))
b


array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37]])

In [13]:
# now we can apply matrix multiplication

a@b

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [14]:
a.dot(b)

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

#### Max()

In [15]:
# maximum element present in that array
b.max()

37

#### Min()

In [16]:
# minimum element present in that array
b.min()

20

#### Argmax()

In [17]:
# finding  index of that maximum  value 
# 37 is present at index 17 in b.

b.argmax()

17

#### Sum()

In [18]:
# sum of all the elements present in the array

np.sum(b)

513

In [19]:
# sum of each and every rows
# axis 1 means rows
# first rows sum value is 135, second is 171, third is 207

np.sum(b,axis = 1)

array([135, 171, 207])

In [20]:
# sum of each and every rows
# Axis 0 means columns
# 1,2,3,4,5,columns sum values is 78,81,84,87,90,93 respectively.

np.sum(b,axis = 0)

array([78, 81, 84, 87, 90, 93])

#### Mean()

In [21]:
np.mean(b)

28.5

#### Median()

In [22]:
np.median(b)

28.5

#### Sqrt()

In [23]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253]])

#### Std()

In [24]:
np.std(b)

5.188127472091127

#### Log()

In [25]:
np.log(b)

array([[2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
        3.4339872 ],
       [3.4657359 , 3.49650756, 3.52636052, 3.55534806, 3.58351894,
        3.61091791]])